"""
Pydantic schemas for chat/tutor endpoints (SEC-3-INPUT).

These schemas provide comprehensive input validation for:
- Sending messages to LLM tutor
- Creating conversations
- Deleting conversations
- Retrieving conversation history

Security Features:
- Message length limits (prevent DoS)
- Markdown sanitization (prevent XSS via markdown)
- Conversation ID validation
- HTML/XSS protection
"""
from typing import Optional
from pydantic import BaseModel, Field, field_validator
import bleach


# ===================================================================
# Markdown Sanitization Configuration
# ===================================================================

# Allowed HTML tags for markdown rendering
ALLOWED_TAGS = [
    'p', 'br', 'strong', 'em', 'u', 's', 'blockquote',
    'code', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'ul', 'ol', 'li', 'hr', 'a', 'img', 'table', 'thead',
    'tbody', 'tr', 'th', 'td',
]

# Allowed attributes for HTML tags
ALLOWED_ATTRIBUTES = {
    'a': ['href', 'title'],
    'img': ['src', 'alt', 'title'],
    'code': ['class'],  # For syntax highlighting (language-python, etc.)
    'pre': ['class'],
}

# Allowed protocols for links (prevent javascript:, data:, etc.)
ALLOWED_PROTOCOLS = ['http', 'https', 'mailto']


def sanitize_markdown(text: str) -> str:
    """
    Sanitize markdown content to prevent XSS attacks.

    Uses bleach library to:
    - Allow safe HTML tags generated by markdown
    - Strip dangerous attributes (onclick, onerror, etc.)
    - Block javascript:, data: protocols in links
    - Escape everything else

    Args:
        text: Raw markdown/HTML content from user

    Returns:
        Sanitized markdown content safe for rendering
    """
    # First strip leading/trailing whitespace
    stripped = text.strip()

    # Use bleach to sanitize
    sanitized = bleach.clean(
        stripped,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        protocols=ALLOWED_PROTOCOLS,
        strip=True  # Strip disallowed tags instead of escaping
    )

    # Linkify is optional - only if we want to auto-convert URLs to links
    # For now, we'll skip it to avoid unexpected behavior

    return sanitized


# ===================================================================
# Request Schemas
# ===================================================================

class SendMessageRequest(BaseModel):
    """
    Schema for sending a message to the LLM tutor.

    Security validations:
    - Message length limits (min 1, max 5000 chars)
    - Markdown sanitization (XSS protection)
    - Optional conversation ID validation
    """
    message: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="User message to send to tutor (supports markdown)"
    )
    conversation_id: Optional[int] = Field(
        None,
        description="Optional conversation ID to continue existing conversation"
    )

    @field_validator('message')
    @classmethod
    def validate_message(cls, value: str) -> str:
        """
        Validate and sanitize message content.

        - Strips leading/trailing whitespace
        - Ensures non-empty after stripping
        - Sanitizes markdown to prevent XSS

        Raises:
            ValueError: If message is empty after stripping
        """
        stripped = value.strip()

        if not stripped:
            raise ValueError("Message cannot be empty or only whitespace")

        # Sanitize markdown content
        sanitized = sanitize_markdown(stripped)

        return sanitized

    @field_validator('conversation_id')
    @classmethod
    def validate_conversation_id(cls, value: Optional[int]) -> Optional[int]:
        """
        Validate conversation ID.

        Raises:
            ValueError: If conversation ID is invalid
        """
        if value is not None and value <= 0:
            raise ValueError("Conversation ID must be a positive integer")

        return value


class CreateConversationRequest(BaseModel):
    """
    Schema for creating a new conversation.

    Security validations:
    - Title length limits
    - HTML sanitization
    """
    title: Optional[str] = Field(
        None,
        max_length=200,
        description="Optional conversation title"
    )

    @field_validator('title')
    @classmethod
    def validate_title(cls, value: Optional[str]) -> Optional[str]:
        """
        Validate and sanitize conversation title.

        - Strips leading/trailing whitespace
        - Escapes HTML entities (XSS protection)
        - Returns None if empty after stripping

        Returns:
            Sanitized title or None
        """
        if value is None:
            return None

        stripped = value.strip()

        if not stripped:
            return None

        # Sanitize HTML
        sanitized = sanitize_markdown(stripped)

        return sanitized


class DeleteConversationRequest(BaseModel):
    """
    Schema for deleting a conversation.

    Note: Conversation ID comes from URL path parameter, not request body.
    This schema is for documentation purposes.
    """
    pass  # No fields - ID comes from URL


# ===================================================================
# Response Schemas
# ===================================================================

class MessageResponse(BaseModel):
    """Response schema for a single message."""
    id: int
    conversation_id: int
    role: str  # "user" or "assistant"
    content: str
    created_at: str


class SendMessageResponse(BaseModel):
    """Response schema for sending a message."""
    user_message: MessageResponse
    assistant_message: MessageResponse
    conversation_id: int


class ConversationSummary(BaseModel):
    """Summary of a conversation for list view."""
    id: int
    title: Optional[str]
    created_at: str
    updated_at: str
    message_count: int
    last_message_preview: Optional[str]


class ConversationListResponse(BaseModel):
    """Response schema for conversation list."""
    conversations: list[ConversationSummary]
    total: int


class ConversationDetailResponse(BaseModel):
    """Response schema for conversation details."""
    id: int
    title: Optional[str]
    created_at: str
    updated_at: str
    messages: list[MessageResponse]


class DeleteConversationResponse(BaseModel):
    """Response schema for conversation deletion."""
    message: str
    conversation_id: int
